apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  DATABASE_NAME: dXNlcmRi
  DATABASE_USER: c2F0eWFt
  DATABASE_PASSWORD: bmFnYXJybw==
  DATABASE_PORT: NTQzMg==
  SERVICE_PORT: ODA4MA==
  BASIC_AUTH_USER: YXV0aF91c2Vy
  BASIC_AUTH_PASSWORD: YXV0aF9wYXNz
  JWT_SECRET_KEY: MTIzNDVfU2F0eWFt
  JWT_EXPIRATION_TIME: NjA=
