apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: development
data:
  GIN_MODE: "debug"
  LOG_FILE_PATH: "./log"
  DATABASE_HOST: "10-244-0-74.postgres-headless.development.svc.cluster.local"
